### ISSUE TITLE
API in README does not appear to match actual API

### ISSUE THREAD

**Issue by wbthomason** [oberblastmeister/neuron.nvim#1]
First off, thanks for making this! I've wanted to play around with `neuron` for a while, and this looks like it'll make it easier and more useful to do so.

When I was trying to get started, I wanted to manually run some of the functions documented in the default keybindings section of the README. However, some of these seem to not exist (at least, under the given name). For example, `new` is not a function, but (per inspection with `print(vim.inspect(require'neuron'))`) `open` is. I'm not sure if the names in the README are for functions that are still in-progress, etc., but it seems that the docs are a bit out of sync with the code.

**Comment by oberblastmeister** [comment]
I have updated the README so that the mappings should be correct. Sorry I forgot to update it because this plugin is in heavy development. Let me know if you have any more questions.

**Comment by wbthomason** [comment]
Thanks, and no worries!

One note (separate from the original issue) is that you may want to add logic to initialize a `neuron.dhall` in the notes directory if none exists already. This briefly confused me when testing.
