### ISSUE TITLE
What is "unstable" branch used for?

### ISSUE THREAD

**Issue by VVKot** [oberblastmeister/neuron.nvim#10]
Is this work which will be eventually merged into master or more of an experiment? Seems that it works with latest neuron binary while master does not. If I want to contribute some of the features from https://github.com/fiatjaf/neuron.vim/ - should I PR them against "unstable"?

**Comment by frandsoh** [comment]
You are right. The unstable branch is for the latest neuron version. See my pull request for a version working with Neuron 1.9.7. You're welcome to review it and comment on it, so we can get it merged.
