### ISSUE TITLE
Telescope's preview doesn't work

### ISSUE THREAD

**Issue by ekickx** [oberblastmeister/neuron.nvim#3]
So I use `lua require'neuron/telescope'.find_zettels()` to find my note and get this error. And telescope doesn't show the preview.

![image](https://user-images.githubusercontent.com/26477782/104111554-cfc2c980-5315-11eb-8a26-1043b1f7ac75.png)

![image](https://user-images.githubusercontent.com/26477782/104111590-3ba53200-5316-11eb-9d56-b62659859938.png)

And then I try to solve it by using `vim.fn.expand()` in my config like this and it works. I guess the problem is either telescope or neuron.nvim doesn't expand the `config_dir` by default. Maybe you can add instruction in the Readme to use `vim.fn.expand()` for `config_dir` to solve this issue. And sorry if my wording is confusing.

![image](https://user-images.githubusercontent.com/26477782/104111636-d30a8500-5316-11eb-9b94-cf090575b10b.png)
![image](https://user-images.githubusercontent.com/26477782/104111670-6479f700-5317-11eb-93a7-b717696d5036.png)

**Comment by oberblastmeister** [comment]
Thank you for filing an issue. Fixed in 22af0a714c3838ffda9a04e508cea2bdc7143ed5
