### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'config' (a nil value)

### ISSUE THREAD

**Issue by ghost** [oberblastmeister/neuron.nvim#39]
I'm using the unstable branch like the docs said with neuron 1.0.1.0, I also tried 1.0.0.0, and I'm getting the following error when trying to create a new note, with the default setup and directory structure of this plugin.

```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'config' (a nil value)
```

My config looks like this.

```lua
  {
    "oberblastmeister/neuron.nvim",
    { branch = "unstable" },
    requires = { { "nvim-lua/popup.nvim" }, { "nvim-lua/plenary.nvim" }, { "nvim-telescope/telescope.nvim" } },
 }
```

**Comment by yutkat** [comment]
`lua require'neuron/cmd'.new_edit(require'neuron'.config.neuron_dir)`
->
`lua require'neuron/cmd'.new_edit(require'neuron/config'.neuron_dir)`

**Comment by ghost** [comment]
@yutkat Thanks, if that was fully on me.
