### ISSUE TITLE
Neuron version?

### ISSUE THREAD

**Issue by frandsoh** [oberblastmeister/neuron.nvim#4]
Are you using neuron v1 or the development version?

**Comment by oberblastmeister** [comment]
I am using neuron v1

**Comment by frandsoh** [comment]
Thanks - 

I'm messing around with your code, to make it work with my setup using neuron 1.9

You're welcome to take a look at my 'develop' branch

Cheers 👍

**Comment by oberblastmeister** [comment]
I have started using the development version of neuron. I merged your branch into my `unstable` branch. You are welcome to make prs to it.

**Comment by frandsoh** [comment]
Fantastic! Let's make something great

**Comment by cooperuser** [comment]
I was having some issues to get neuron.nvim to work a week or so ago, I think that may have been do to version problems. The first I've heard about neuron and this style of notetaking was from this repo, so I didn't know exactly how to get it working. I'll try again and mess around with different versions.
