### ISSUE TITLE
<cr> on link to new Zettel claims "no link under cursor"

### ISSUE THREAD

**Issue by wbthomason** [oberblastmeister/neuron.nvim#6]
This could be a mismatch in my expectations for how `neuron` is designed to work, but: I had thought that pressing `<cr>` on a link to a nonexistent page would create that page in my `neuron` root. Instead, it appears that `neuron.nvim` only considers links to already extant pages valid. Would it be possible to make `<cr>` create new pages where necessary, or is that not the intent of the tool? Thanks!

**Comment by oberblastmeister** [comment]
Pressing `<cr>` will not create a new page. However, that would be a cool feature and I can work on it.

**Comment by oberblastmeister** [comment]
Also what `neuron` version are you using? Most development for this plugin has moved to the newest neuron version which is available on the `unstable` branch. I should probably add that to the `README.md`

**Comment by wbthomason** [comment]
fwiw, it appears that part of the problem is that the link regexes hard-code the default 8-character random ID pattern that `neuron` generates: https://github.com/oberblastmeister/neuron.nvim/blob/22af0a714c3838ffda9a04e508cea2bdc7143ed5/lua/neuron/utils.lua#L47-L48

> Also what neuron version are you using? Most development for this plugin has moved to the newest neuron version which is available on the unstable branch. I should probably add that to the README.md

I'm using the latest stable release; I didn't know that this plugin was tailored for the pre-release version. Good to know, thanks!

**Comment by oberblastmeister** [comment]
the regex problem should be fixed in the `unstable` branch
