### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by skbolton** [oberblastmeister/neuron.nvim#9]
When I follow the installation instructions and try to run `lua require'neuron/telescope'.find_zettels()` I get the following error 
```
Error executing vim.schedule lua callback: .../site/pack/packer/start/neuron.nvim/lua/neuron/utils.lua:27: Vim(echoerr):An error occured from running neuron query: ^[[90m   Plugins enabled: links, tags, neuronignore, uptree^[[0m
```

This seems to match the output I see when I run `neuron new` in my terminal. Is stdout being interpretted as stderrr?
```
$ neuron new
   Plugins enabled: links, tags, neuronignore, uptree
   Loading directory tree (1 .md files) ...
   Building graph (1 notes) ...
/home/orlando/neuron/f6d7abe3.md
$
```

**Comment by frandsoh** [comment]
Which version of Neuron are you using? `neuron --version`

The master branch is targeting neuron v1. The unstable is for neuron 1.9.4 (if I remember correctly)

See my pull request for a version for neuron 1.9.7.x

**Comment by skbolton** [comment]
Yeah the newest version installed (1.9.7)

**Comment by skbolton** [comment]
Tested out your branch @frandsoh and the error did go away.

**Comment by skbolton** [comment]
I have moved to version `1.0.1.0` of neuron and everything is working. It seems like this is the intended version that should be used.
